apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-api
  description: Demo API service deployed via GitOps on DevPath IDP
  annotations:
    github.com/project-slug: doyindevops/catalog-api-local-4
spec:
  type: service
  lifecycle: production
  owner: guests
  system: devpath-platform
